language: node_js
node_js:
 - "8.9.1"
branches:
  only:
    - development
script:
 - npm test
after_success:
  - CODECLIMATE_REPO_TOKEN=193cae913542dcffca3a12c1e2aa8b854cba67e2630d71a1a429708edb7112b6 codeclimate-test-reporter < coverage/lcov.info
  - npm run coverage
