language: node_js
node_js:
 - "8.9.1"
script:
 - npm test
services:
  -postgresql
before_script:
  - psql -c 'CREATE DATABASE travis;' -U postgres
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
after_success:
  - npm run coveralls
  - npm run coverage
  - npm run report-coverage
  - npm run codeclimate-report
  