language: node_js
node_js:
 - "8.9.1"
branches:
  only:
    - development
script:
 - npm test
after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < coverage/lcov.info
  - npm run coverage
