language: node_js
node_js:
 - "8.9.1"
branches:
  only:
    - development
script:
 - npm test
after_success:
  - CODECLIMATE_REPO_TOKEN=b7070f36a7a8acb33ca02b7543476778b82657295746ed309c179a51faae1852 codeclimate-test-reporter < ./coverage/lcov.info
  - npm run coverage
